In [2]:
import numpy as np

In [47]:
n = 3

In [48]:
A = np.diag(np.ones(n - 1), 1) + np.diag(np.ones(n) * 2) + np.diag(np.ones(n - 1), -1);
A

array([[2., 1., 0.],
       [1., 2., 1.],
       [0., 1., 2.]])

In [49]:
A.shape

(3, 3)

In [50]:
np.linalg.det(A)

4.0

In [60]:
a_1 = np.array([1, -1, 1, -1])
a_2 = np.array([1, 1, 1, 1])
x = np.array([19, 5, 5, -1])

In [62]:
x @ a_1, a_1 @ a_1, a_2 @ a_1

(20, 4, 0)

In [63]:
x @ a_2, a_1 @ a_2, a_2 @ a_2

(28, 0, 4)

In [65]:
p_1 = 20 / 4
p_2 = 28 / 4

In [66]:
p_1, p_2

(5.0, 7.0)

In [67]:
p_1 * a_1 + p_2 * a_2

array([12.,  2., 12.,  2.])

In [85]:
p_1 = 12
p_2 = (28 - 4 * p_1) / 2

In [59]:
p_1 * a_1 + p_2 * a_2

array([12.,  2., 12.,  2.])

In [68]:
def f(n):
    return (np.arange(n - 1) / (n ** 2)).sum()

In [76]:
f(10000)

0.49985000999999996

In [79]:
a, b, r = 9, 13, 3
pi = 3.141592654
pi * (r ** 2) / (a * b * 4)

0.06041524334615385

In [81]:
np.linalg.eig([[1, 2], [3, 4]])[0]

array([-0.37228132,  5.37228132])

In [84]:
np.linalg.eig([[-129, 116], [-149, 134]])[0]

array([-0.37228132,  5.37228132])

In [87]:
s = np.array([30, 20, 20])
p = np.array([0.9, 0.75, 0.8])

In [92]:
P_Vszg = (s / s.sum()) * p

In [95]:
np.around(P_Vszg / P_Vszg.sum(), 4)b

array([0.4655, 0.2586, 0.2759])

In [ ]:
!

In [102]:
if __name__ == '__main__':
    with open('input.txt', 'r') as f:
        n = int(f.readline())
        nums = [int(i) for i in f.readline().split()]
    
    result = len(nums) - len(set(nums))
    result = str(result)
    
    with open('output.txt', 'w') as f:
        f.write(result)
        f.write('\n')

In [122]:
if __name__ == '__main__':
    with open('input.txt', 'r') as f:
        n = int(f.readline())
        d = [int(i) for i in f.readline().split()]
        assert len(d) == n
    
    l, r = [d[0] + 1] * len(d), [d[-1] + 1] * len(d)
    
    for i in range(1, len(d)):
        l[i] = l[i - 1] + d[i] + 1
        
    for i in range(len(d) - 2, 0, -1):
        r[i] = r[i + 1] + d[i] + 1
    
    s = r[1]
    for i in range(1, len(d) - 1):
        s += l[i] * r[i + 1]
        s += d[i] * (l[i - 1] + r[i + 1] + d[i])
    
    result = str(s)
    
    with open('output.txt', 'w') as f:
        f.write(result)
        f.write('\n')

In [213]:
import math


def mod_pow(a, x, p):
    res = 1
    while x > 0:
        if (x % 2 != 0):
            res = (res * a) % p
        a = (a ** 2) % p
        x = x // 2
    return res


def mod_inv(a, p):
    return mod_pow(a, p - 2, p)


def binomial(n, k, p):
    num = 1
    for i in range(k):
        num = (num * (n - i)) % p
    
    dem = 1
    for i in range(1, k + 1):
        dem = (dem * i) % p
    
    return (num * mod_inv(dem, p)) % p

if __name__ == '__main__':
    with open('input.txt', 'r') as f:
        k, n = [int(i) for i in f.readline().split()]
        l, m = [int(i) for i in f.readline().split()]
    
    p = 1000000007
    result = str(math.gcd(binomial(n, k, p), binomial(m, l, p)) % p)
    with open('output.txt', 'w') as f:
        f.write(result)
        f.write('\n')

In [214]:
!cat output.txt

2
